watchAnyNamespace: false
watchNamespaces:
  - streaming

resources:
  requests:
    cpu: 200m
    memory: 384Mi
  limits:
    cpu: 500m
    memory: 512Mi

logLevel: INFO

leaderElection:
  enabled: true

featureGates: ""
