replicaCount: 1

webhook:
  enable: true
  port: 9443

controller:
  workers: 10

spark:
  jobNamespaces:
    - processing
  serviceAccount:
    create: true
    name: spark

logLevel: 2

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

rbac:
  create: true
