replicaCount: 1

webhook:
  enable: true
  port: 9443

controller:
  workers: 10
  namespaces:
    - processing

logLevel: 2

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

serviceAccounts:
  spark:
    create: true
    name: spark

rbac:
  create: true
