apiVersion: v1
kind: Namespace
metadata:
  name: argocd
---
apiVersion: v1
kind: Namespace
metadata:
  name: infra
---
apiVersion: v1
kind: Namespace
metadata:
  name: streaming
---
apiVersion: v1
kind: Namespace
metadata:
  name: processing
---
apiVersion: v1
kind: Namespace
metadata:
  name: orchestration
---
apiVersion: v1
kind: Namespace
metadata:
  name: serving
---
apiVersion: v1
kind: Namespace
metadata:
  name: governance
---
apiVersion: v1
kind: Namespace
metadata:
  name: portal
