replicaCount: 1

resources:
  requests:
    memory: 1.5Gi
    cpu: 500m
  limits:
    memory: 3Gi
    cpu: 2000m

global:
  airflow:
    enabled: false

deps:
  mysql:
    enabled: true
  elasticsearch:
    enabled: false
