apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nessie
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://charts.projectnessie.org
      chart: nessie
      targetRevision: "0.107.5"
      helm:
        valueFiles:
          - $values/helm/nessie/values.yaml
    - repoURL: git@github.com:sergiopassos/data-platform-on-premise.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
