apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openmetadata
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/sergiopassos/data-platform-on-premise
    targetRevision: HEAD
    path: helm/openmetadata
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: governance
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
