apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-manifests
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:sergiopassos/data-platform-on-premise.git
    targetRevision: HEAD
    path: manifests/platform
  destination:
    server: https://kubernetes.default.svc
    namespace: orchestration
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
