apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spark-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://kubeflow.github.io/spark-operator
      chart: spark-operator
      targetRevision: "2.1.0"
      helm:
        skipCrds: true
        valueFiles:
          - $values/helm/spark-operator/values.yaml
    - repoURL: git@github.com:sergiopassos/data-platform-on-premise.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: processing
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - Replace=true
