apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spark-jobs
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:sergiopassos/data-platform-on-premise.git
    targetRevision: HEAD
    path: spark
  destination:
    server: https://kubernetes.default.svc
    namespace: processing
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
