apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trino
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://trinodb.github.io/charts
      chart: trino
      targetRevision: "0.29.0"
      helm:
        valueFiles:
          - $values/helm/trino/values.yaml
    - repoURL: git@github.com:sergiopassos/data-platform-on-premise.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: serving
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
