versionStoreType: ROCKSDB

deploymentStrategy:
  type: Recreate

rocksdb:
  storageClassName: standard
  storageSize: 1Gi

replicaCount: 1

resources:
  requests:
    memory: 512Mi
    cpu: 250m
  limits:
    memory: 1Gi
    cpu: 500m

service:
  type: ClusterIP
  port: 19120

catalog:
  enabled: true
  iceberg:
    defaultWarehouse: warehouse
    warehouses:
      - name: warehouse
        location: s3://warehouse/
      - name: bronze
        location: s3://bronze/
  storage:
    s3:
      defaultOptions:
        region: us-east-1
        endpoint: http://minio.infra.svc.cluster.local:9000
        pathStyleAccess: true
        authType: STATIC
        accessKeySecret:
          name: nessie-minio-creds
          awsAccessKeyId: aws-access-key-id
          awsSecretAccessKey: aws-secret-access-key
