mysql:
  enabled: true
  fullnameOverride: "mysql"
  image:
    tag: "latest"
  auth:
    rootPassword: "password"
    username: "openmetadata_user"
    password: "openmetadata_password"
    database: "openmetadata_db"
  primary:
    resources:
      requests:
        memory: 512Mi
        cpu: 250m
      limits:
        memory: 1Gi
        cpu: 500m

airflow:
  enabled: false

opensearch:
  enabled: false
