mode: standalone

auth:
  rootUser: minio
  rootPassword: minio123

defaultBuckets: "warehouse"

persistence:
  enabled: true
  size: 100Gi

resources:
  requests:
    memory: 1Gi
    cpu: 500m
  limits:
    memory: 2Gi
    cpu: 1000m

service:
  type: ClusterIP
  port: 9000

consoleService:
  type: ClusterIP
  port: 9001

ingress:
  enabled: false

consoleIngress:
  enabled: false

environment:
  MINIO_BROWSER: "on"
  MINIO_REGION_NAME: "us-east-1"
